---
- functions:
  - {name: fromJust, within: []}

- error: {lhs: "convertBool . f . fromIntegral", rhs: "asTest f", name: "Use asTest"}
- error: {lhs: "fromIntegral . f . fromIntegral", rhs: "conjugate f", name: "Use conjugate"}
